[features]
resolution = true
skip-lint = true

[hooks]

[programs.devnet]
stakr_market = "BE3ERuEVgYTN8a9XfW8wpAPg4aTuwPD69RkiAs1fDEaw"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "/mnt/c/Users/User1/.config/solana/id.json"

[scripts]
test = "cargo test"

[toolchain]
anchor_version = "0.30.1"
